[package]
name = "harbinger"
version = "1.0.0"
entrypoint = "lib.typ"
authors = ["Typst Community", "igidrau", "DVDTSB", "ntjess", "PgSuper"]
license = "MIT"
description = "A package for shadow boxes in Typst."
